version: "3.6"
services:
  newrelic:
    networks:
      - main
    container_name: test-project-newrelic
    image: newrelic/php-daemon
  php:
    build:
      context: './docker/php'
      dockerfile: Dockerfile
      args:
        NEWRELIC_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        NEWRELIC_APP_NAME: "Some Test Application"
        NEWRELIC_DAEMON_ADDRESS: "newrelic:31339"
    volumes:
      - ./app:/var/www/html
    networks:
      - main
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main
networks:
  main:
